/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c4c7c8",
        "surface-variant": "#353434",
        "outline-variant": "#444748",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "surface": "#141313",
        "surface-dim": "#141313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353434",
        "secondary": "#c7c6c6",
        "secondary-container": "#484949",
        "on-secondary-container": "#b8b8b8",
        "primary": "#ffffff",
        "on-primary": "#2f3131",
        "on-primary-container": "#636565",
        "primary-container": "#e2e2e2",
        "tertiary": "#ffffff",
        "on-tertiary": "#2f3131",
        "on-tertiary-container": "#636565",
        "tertiary-container": "#e2e2e2",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#8e9192",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#5d5f5f",
        "background": "#141313",
        "on-background": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
        card: "32px",
      },
      spacing: {
        "section-gap": "120px",
        gutter: "24px",
        "container-max": "1280px",
        unit: "8px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "76px", letterSpacing: "-0.05em", fontWeight: "300" }],
        "label-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "400" }],
        "display-lg-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.04em", fontWeight: "300" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
